name: Theo dõi BCTC

on:
  schedule:
    - cron: '*/5 * * * *'   # Chạy mỗi 5 phút
  workflow_dispatch:        # Cho phép trigger thủ công

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup Java 21
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21
        cache: maven

    - name: Restore hashes folder cache
      uses: actions/cache@v3
      with:
        path: hashes
        key: theo-doi-bctc-hashes
        restore-keys: theo-doi-bctc-hashes

    - name: Ensure hashes folder exists and has a file
      run: |
        mkdir -p hashes
        touch hashes/.keep

    - name: Build with Maven
      run: mvn clean compile

    - name: Run the tracker
      run: mvn exec:java -Dexec.mainClass="com.theodoibctc.App"

    - name: Save hashes folder cache
      if: always()
      uses: actions/cache@v3
      with:
        path: hashes
        key: theo-doi-bctc-hashes
