name: TheoDoiBCTC

on:
  schedule:
    - cron: '*/5 * * * *'    # chạy mỗi 5 phút
  workflow_dispatch:         # cho phép chạy thủ công

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Restore cache for hashes
        uses: actions/cache@v3
        with:
          path: hashes
          key: theo-doi-bctc-hashes

      - name: Build project
        run: mvn clean compile

      - name: Run app to check updates
        run: mvn exec:java -Dexec.mainClass=com.theodoibctc.App

      - name: Save cache for hashes
        uses: actions/cache@v3
        with:
          path: hashes
          key: theo-doi-bctc-hashes
