name: Theo dõi BCTC

on:
  schedule:
    - cron: '*/5 * * * *' # Chạy mỗi 5 phút
  workflow_dispatch:       # Cho phép chạy thủ công

jobs:
  run-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Restore cached hashes
        uses: actions/cache@v3
        with:
          path: hashes
          key: theo-doi-bctc-hashes-${{ github.run_id }}
          restore-keys: theo-doi-bctc-hashes-

      - name: Build with Maven
        run: mvn -B clean compile

      - name: Run website check
        run: mvn exec:java -Dexec.mainClass="com.theodoibctc.App"

      - name: Save updated hashes
        uses: actions/cache/save@v3
        if: always()
        with:
          path: hashes
          key: theo-doi-bctc-hashes-${{ github.run_id }}
